name: CI

on:
  push:
    branches: [ integration ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Build nodejs application
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
        run: cd Front && npm install \
          cd Front && npm run build

      # Build java application
      - uses: actions/setup-java@v1
        with:
          java-version: 11
        run: mkdir -p Back/src/main/resources/assets || true && cp -r Front/dist/* Back/src/main/resources/assets \
          cd Back && mvn clean package


      # Copy assets required to build the image
      - name: Copy built application package for docker
        run: cp Back/target/GI.war Docker/CI/build/GI.war

      # Deploy application to heroku
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: "genshin-application-ci"
          dockerfile: "Docker/CI"
